"""
Django settings for SIH_Meraki project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.commands.runserver import Command as runserver

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = BASE_DIR / 'SIH_Meraki/templates'
STATIC_DIR = BASE_DIR / 'SIH_Meraki/static'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pb1+v@wt1m$8n18*0f&ijaw(8+zq#05o#4&vq%8+*nd05gky_g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = ['*']

runserver.default_addr = '0.0.0.0'
runserver.default_port = '8080'

# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'accounts',
    'national',
    'states',
    'districts',
    'talukas',
    'schools',
    'bootstrap4',
    'rest_framework',
    'corsheaders'
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# SECURE_SSL_REDIRECT = True
# SECURE_REDIRECT_EXEMPT = [r'/.*localhost:8080.*/gm',]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]
REST_FRAMEWORK={ 'DEFAULT_PERMISSION_CLASSES': [   'rest_framework.permissions.AllowAny' ]}
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'SIH_Meraki.urls'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ORIGIN_WHITELIST = [
     'http://localhost:3000'
]
    
ROOT_URLCONF = 'SIH_Meraki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SIH_Meraki.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {

    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'sihdjangodb',
    #     'USER': 'sihdjangoadmin',
    #     'PASSWORD': 'Te@mMerak1',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    # }
    
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'sihdb',
    #     'USER': 'postgres',
    #     'PASSWORD': '9223320271',
    #     'HOST': '13.232.44.46',
    #     'PORT': '58945',
    # }
    
    
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangodbsih',
        'USER': 'sihdjangoadmin',
        'PASSWORD': 'Te@mMerak1',
        'HOST': '43.205.168.182',
        'PORT': '51399',
    }

}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles/'
STATICFILES_DIRS = [STATIC_DIR, ]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'



# Email Settings section
# https://docs.djangoproject.com/en/4.0/topics/email/#topic-email-file-backend

USE_REAL_EMAIL_GMAIL = True

if USE_REAL_EMAIL_GMAIL:
    EMAIL_USE_TLS = True
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = 'sih.team.merakii@gmail.com'
    EMAIL_HOST_PASSWORD = 'kopsbkdwqhpemuio'

if DEBUG and not USE_REAL_EMAIL_GMAIL:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "sent_emails"

    
    
    
    